// Traduzioni base (puoi estendere tutte le chiavi che vuoi)
const translations = {
    en: {
    calendar_instructions: `<strong>How to book:</strong> <br>• <em>Single click</em>: Click one day, then another to select the period<br>• <em>Drag</em>: Click and drag to select a period<br><strong>Valid booking:</strong> at least 2 days`,
		// Transport
		location_transport_station: "🚂 <strong>Central Station</strong> - 850m",
		location_transport_airport: "✈️ <strong>Marconi Airport</strong> - 7km",
		// Restaurants
		location_restaurant_valerio: "🍝 <strong>Tavern Valerio</strong> - 10m",
		location_restaurant_altrogusto: "🍽️ <strong>L'Altro Gusto</strong> - 200m",
		location_restaurant_pistamentuccia: "🍕 <strong>Pistamentuccia</strong> - 200m",
        navbar_brand: "B&B Avesella House",
        nav_home: "Home",
        nav_gallery: "Photos",
        nav_features: "The Apartment",
        nav_services: "Included Services",
        nav_location: "Location",
        nav_availability: "Availability",
        nav_rules: "Rules",
        nav_faq: "FAQ",
        nav_contacts: "Contacts",
        home_title: "B&B Avesella House",
        home_subtitle: "Your elegant apartment in the historic center of Bologna",
        home_desc: "📍 Located in the center of Bologna, 600 meters from Mambo Museum of Modern Art and 300 meters from Via dell'Indipendenza. Complete apartment with free WiFi and air conditioning in a historic 1890 building.",
        home_book_btn: "Book now",
        gallery_title: "Photos",
        gallery_living_title: "Living Room",
        gallery_living_desc: "Elegant, clean and comfortable environment.",
		gallery_living_title2: "Dining Area",
        gallery_living_desc2: "Large, bright and welcoming space.",
        gallery_dining_title: "Dining Area",
        gallery_dining_desc: "Large, bright and welcoming space.",
        gallery_kitchen_title: "Kitchen",
        gallery_kitchen_desc: "Modern and fully equipped for every need.",
        gallery_bedroom_title: "Bedroom",
        gallery_bedroom_desc: "Spacious, elegant, welcoming and with all comforts.",
        gallery_bedroom_desc2: "Equipped with extra pillows and blankets for every need.",
        gallery_bedroom_desc3: "Elegant and functional with all comforts.",
        gallery_bathroom_title: "Bathroom",
        gallery_bathroom_desc: "Clean, modern and functional.",
		gallery_court_title: "Court",
		gallery_court_desc: "Elegant and refined context.",
        gallery_entrance_title: "Entrance",
        gallery_entrance_desc: "Elegant and refined context.",
        gallery_elevator_title: "Elevator",
        gallery_elevator_desc: "Elevator with key available.",
        gallery_door_title: "Main Door",
        gallery_door_desc: "Wooden main door.",
        gallery_building_title: "Palace",
        gallery_building_desc: "Palace with portico for rain protection.",
        features_title: "The Apartment",
        features_lead: "🏛️ Complete apartment in a historic 1890 building in the center of Bologna",
        features_details: "📐 70 m² • 🛏️ 1 bedroom • 🛁 1 private bathroom • 👥 Entire accommodation for you",
        features_spaces: "🏠 Spaces",
        features_living: "🍽️ Living Room",
        features_living_desc: "TV<br>Sofa",
        features_kitchen: "🍳 Kitchen",
        features_kitchen_desc: "Stove<br>Fridge<br>Microwave oven<br>Kettle<br>Coffee machine<br>Dishwasher",
        features_bedroom: "🛏️ Bedroom",
        features_bedroom_desc: "Double bed<br>TV<br>Wardrobe<br>Desk",
        features_bathroom: "🚿 Private Bathroom",
        features_bathroom_desc: "WC<br>Bidet<br>Shower<br>Towels<br>Hairdryer<br>Shower gel<br>Shampoo",
        services_title: "Included Services",
        services_internet: "📶 Internet",
        services_internet_desc: "Free fast WiFi<br>",
        services_climate: "❄️🔥 Air Conditioning",
        services_climate_desc: "Air conditioning<br>and heating",
        services_entertainment: "📺 Entertainment",
        services_entertainment_desc: "Flat screen TV<br>in living room and bedroom",
        services_comfort: "🛗 Comfort",
        services_comfort_desc: "Elevator",
        services_work: "💼 Work",
        services_work_desc: "Desk",
        services_languages: "🗣️ Languages",
        services_languages_desc: "English<br>Italian",
		location_title: "Location & Surroundings",
		location_lead: "B&B Avesella House is located in the historic center of Bologna, surrounded by historic buildings and just a few steps from the city's main attractions. A stone's throw from Via dell'Indipendenza for walks and shopping in the center.",
		location_main_attractions: "🏛️ Main Attractions",
		location_historic_buildings: "🏰 Historic Buildings",
		location_transport: "🚌 Transport",
		location_attraction_arena: "🎭 <strong>Theater Arena del Sole</strong> - 230m",
		location_attraction_ottoagosto: "⛲ <strong>Square Otto Agosto</strong> - 300m",
		location_attraction_montagnola: "🌳 <strong>Park Montagnola</strong> - 400m",
		location_attraction_manzoni: "🎭 <strong>Theater Manzoni</strong> - 500m",
		location_attraction_medievale: "🎨 <strong>Medieval Civic Museum</strong> - 500m",
		location_attraction_fava: "🎨 <strong>Fava Palace</strong> - 500m",
		location_attraction_mambo: "🖼️ <strong>Mambo Museum</strong> - 550m",
		location_attraction_maggiore: "⛲ <strong>Square Maggiore</strong> - 850m",
		location_attraction_macchina: "🎭 <strong>Time Machine</strong> - 900m",
		location_attraction_pinacoteca: "🖼️ <strong>National Art Gallery</strong> - 1.1km",
		location_attraction_giardini: "🌳 <strong>Margherita Gardens</strong> - 2.5km",
		location_building_bonasoni: "🏛️ <strong>Bonasoni Palace</strong> - 150m",
		location_building_felicini: "🏛️ <strong>Felicini Palace</strong> - 150m",
		location_building_merendoni: "🏛️ <strong>Merendoni Palace</strong> - 200m",
		location_building_garibaldi: "🗿 <strong>Garibaldi Statue</strong> - 300m",
		location_building_tuate: "🏠 <strong>Casa delle Tuate</strong> - 300m",
		location_building_dalmonte: "🏛️ <strong>Dal Monte Palace</strong> - 300m",
		location_building_govese: "🚪 <strong>Govese Gate</strong> - 400m",
		location_building_faccetta: "🏛️ <strong>Faccetta Nera Palace</strong> - 450m",
		location_building_nettuno: "⛲ <strong>Neptune Statue</strong> - 900m",
        location_restaurants: "🍽️ Restaurants",
        availability_title: "Availability & Prices",
        availability_book_btn: "Book",
        rules_title: "Rules & Information",
        rules_times: "🕐 Times & Check-in",
        rules_arrival: "🕐 <strong>Arrival:</strong> from 15:00 to 18:00",
        rules_notify: "📞 <strong>Please notify your arrival time in advance</strong>",
        rules_departure: "🕐 <strong>Departure:</strong> by 11:00",
        rules_no_age_limit: "🔞 <strong>No minimum age for check-in</strong>",
        rules_not_allowed: "🚫 Not Allowed",
        rules_no_smoking: "🚭 <strong>Smoking is not allowed</strong>",
        rules_no_parties: "🎉 <strong>No parties/events allowed</strong>",
        rules_no_pets: "🐕 <strong>No pets allowed</strong>",
        rules_no_candles: "🕯️ <strong>No candles or incense allowed</strong>",
        rules_no_loud_music: "🔊 <strong>No loud music or parties</strong>",
        rules_quiet: "🤫 Quiet Hours",
        rules_quiet_afternoon: "🕐 <strong>From 14:00 to 16:00</strong> (afternoon rest)",
        rules_quiet_night: "🌙 <strong>From 23:00 to 08:00</strong> (night rest)",
        rules_guidelines: "⚠️ Guidelines",
        rules_only_guests: "👥 <strong>Only registered guests are allowed</strong>",
        rules_slippers: "🥿 <strong>Disposable slippers provided for the room</strong>",
        rules_no_luggage: "🧳 <strong>Do not drag suitcases on the parquet</strong>",
        rules_responsible_use: "🌍 <strong>Responsible use of water and electricity</strong>",
        rules_keys: "🔑 <strong>Be careful with keys - lock replacement at guest's expense</strong>",
        rules_report_damage: "⚠️ <strong>Report any damage or incident immediately</strong>",
        rules_extra_beds: "🛏️ Extra Beds",
        rules_no_extra_beds: "❌ <strong>No cots or extra beds available</strong>",
        faq_title: "Frequently Asked Questions",
        faq_parking_q: "🅿️ Where can I park?",
        faq_parking_a: "There are paid public parking lots in the historic center.",
        faq_wifi_q: "📶 Is WiFi included?",
        faq_wifi_a: "Yes, fast free WiFi (343 Mbps) is available throughout the apartment.",
        faq_ac_q: "❄️ Is there air conditioning?",
        faq_ac_a: "Yes, the apartment has air conditioning and heating.",
        faq_elevator_q: "🛗 Is there an elevator?",
        faq_elevator_a: "Yes, the 1890 historic building has an elevator.",
        faq_extra_beds_q: "🛏️ Are extra beds available?",
        faq_extra_beds_a: "No extra beds are available.",
        faq_pets_q: "🐕 Can I bring pets?",
        faq_pets_a: "No, pets are not allowed in the apartment.",
        contacts_title: "Contacts",
        contacts_email_label: "Email:",
        contacts_phone_label: "Phone:",
        contacts_languages_label: "Languages spoken:",
        contacts_whatsapp_btn: "💬 Contact us on WhatsApp",
        footer_copyright: "© 2025 B&B Avesella House"
    },
    it: {
    calendar_instructions: `<strong>Come prenotare:</strong> <br>• <em>Click singolo</em>: Clicca su un giorno, poi su un altro per selezionare il periodo<br>• <em>Trascina</em>: Clicca e trascina per selezionare un periodo<br><strong>Prenotazione valida:</strong> di almeno 2 giorni`,
		// Mezzi di Trasporto
		location_transport_station: "🚂 <strong>Stazione Centrale</strong> - 850m",
		location_transport_airport: "✈️ <strong>Aeroporto Marconi</strong> - 7km",
		// Ristoranti
		location_restaurant_valerio: "🍝 <strong>Trattoria Valerio</strong> - 10m",
		location_restaurant_altrogusto: "🍽️ <strong>L'Altro Gusto</strong> - 200m",
		location_restaurant_pistamentuccia: "🍕 <strong>Pistamentuccia</strong> - 200m",
        navbar_brand: "B&B Avesella House",
        nav_home: "Home",
        nav_gallery: "Foto",
        nav_features: "Appartamento",
        nav_services: "Servizi",
        nav_location: "Posizione",
        nav_availability: "Disponibilità",
        nav_rules: "Regole",
        nav_faq: "FAQ",
        nav_contacts: "Contatti",
        home_title: "B&B Avesella House",
        home_subtitle: "Il tuo appartamento elegante nel centro storico di Bologna",
        home_desc: "📍 Posizionato al centro di Bologna, a 600 metri da Mambo Museo di Arte Moderna e 300 metri da Via dell'Indipendenza. Appartamento completo con WiFi gratuito e aria condizionata in edificio storico del 1890.",
        home_book_btn: "Prenota ora",
        gallery_title: "Foto",
        gallery_living_title: "Soggiorno",
        gallery_living_desc: "Ambiente elegante, pulito e confortevole.",
        gallery_living_desc2: "Confortevole per il vostro soggiorno.",
        gallery_dining_title: "Zona Pranzo",
        gallery_dining_desc: "Ampio spazio luminoso e accogliente.",
        gallery_kitchen_title: "Cucina",
        gallery_kitchen_desc: "Moderna e completamente attrezzata per ogni esigenza.",
        gallery_bedroom_title: "Camera da letto",
        gallery_bedroom_desc: "Spaziosa, elegante, accogliente e con tutti i comfort.",
        gallery_bedroom_desc2: "Attrezzata con cuscini e coperte aggiuntive per ogni esigenza.",
        gallery_bedroom_desc3: "Elegante e funzionale con tutti i comfort.",
        gallery_bathroom_title: "Bagno",
        gallery_bathroom_desc: "Pulito, moderno e funzionale.",
        gallery_entrance_title: "Ingresso",
        gallery_entrance_desc: "Contesto signorile e raffinato.",
        gallery_elevator_title: "Ascensore",
        gallery_elevator_desc: "A disposizione ascensore con chiave.",
        gallery_door_title: "Portone",
        gallery_door_desc: "Portone in legno.",
        gallery_building_title: "Palazzo",
        gallery_building_desc: "Palazzo con portico per protezione in caso di pioggia.",
        features_title: "L'Appartamento",
        features_lead: "🏛️ Appartamento completo in edificio storico del 1890 nel centro di Bologna",
        features_details: "📐 70 m² • 🛏️ 1 camera da letto • 🛁 1 bagno privato • 👥 Intero alloggio per te",
        features_spaces: "🏠 Spazi",
        features_living: "🍽️ Soggiorno",
        features_living_desc: "TV<br>Divano",
        features_kitchen: "🍳 Cucina",
        features_kitchen_desc: "Fornelli<br>Frigo<br>Forno a microonde<br>Bollitore elettrico<br>Macchina del caffè<br>Lavastoviglie",
        features_bedroom: "🛏️ Camera da letto",
        features_bedroom_desc: "Letto Matrimoniale<br>TV<br>Armadio<br>Scrivania",
        features_bathroom: "🚿 Bagno privato",
        features_bathroom_desc: "WC<br>Bidet<br>Doccia<br>Asciugamani<br>Asciugacapelli<br>Bagnoschiuma<br>Shampoo",
        services_title: "Servizi Inclusi",
        services_internet: "📶 Internet",
        services_internet_desc: "WiFi veloce gratuito<br>",
        services_climate: "❄️🔥 Climatizzazione",
        services_climate_desc: "Aria condizionata<br>e riscaldamento",
        services_entertainment: "📺 Intrattenimento",
        services_entertainment_desc: "TV a schermo piatto<br>nel soggiorno e in camera",
        services_comfort: "🛗 Comodità",
        services_comfort_desc: "Ascensore",
        services_work: "💼 Lavoro",
        services_work_desc: "Scrivania",
        services_languages: "🗣️ Lingue",
        services_languages_desc: "Inglese<br>Italiano",
		location_title: "Posizione e Dintorni",
		location_lead: "B&B Avesella House si trova nel centro storico di Bologna, circondato da palazzi storici e a pochi passi dalle principali attrazioni della città. A due passi da via dell'Indipendenza per passeggiate e shopping nel centro.",
		location_main_attractions: "🏛️ Attrazioni Principali",
		location_historic_buildings: "🏰 Palazzi Storici",
		location_transport: "🚌 Mezzi di Trasporto",
		location_attraction_arena: "🎭 <strong>Teatro Arena del Sole</strong> - 230m",
		location_attraction_ottoagosto: "⛲ <strong>Piazza dell'Otto Agosto</strong> - 300m",
		location_attraction_montagnola: "🌳 <strong>Parco della Montagnola</strong> - 400m",
		location_attraction_manzoni: "🎭 <strong>Teatro Manzoni</strong> - 500m",
		location_attraction_medievale: "🎨 <strong>Museo Civico Medievale </strong> - 500m",
		location_attraction_fava: "🎨 <strong>Palazzo Fava</strong> - 500m",
		location_attraction_mambo: "🖼️ <strong>Museo Mambo</strong> - 550m",
		location_attraction_maggiore: "⛲ <strong>Piazza Maggiore</strong> - 850m",
		location_attraction_macchina: "🎭 <strong>Macchina del Tempo</strong> - 900m",
		location_attraction_pinacoteca: "🖼️ <strong>Pinacoteca Nazionale</strong> - 1.1km",
		location_attraction_giardini: "🌳 <strong>Giardini Margherita</strong> - 2.5km",
		location_attraction_arena: "🎭 <strong>Arena del Sole Theatre</strong> - 230m",
		location_attraction_ottoagosto: "⛲ <strong>Piazza dell'Otto Agosto</strong> - 300m",
		location_attraction_montagnola: "🌳 <strong>Montagnola Park</strong> - 400m",
		location_attraction_manzoni: "🎭 <strong>Manzoni Theatre</strong> - 500m",
		location_attraction_medievale: "🎨 <strong>Medieval Civic Museum</strong> - 500m",
		location_attraction_fava: "🎨 <strong>Fava Palace</strong> - 500 m",
		location_attraction_mambo: "🖼️ <strong>Mambo Museum</strong> - 550 m",
		location_attraction_maggiore: "⛲ <strong>Piazza Maggiore</strong> - 850 m",
		location_attraction_macchina: "🎭 <strong>Time Machine</strong> - 900 m",
		location_attraction_pinacoteca: "🖼️ <strong>National Art Gallery</strong> - 1.1 km",
		location_attraction_giardini: "🌳 <strong>Margherita Gardens</strong> - 2.5 km",
		location_transport_station: "🚂 <strong>Stazione Centrale</strong> - 850m",
		location_transport_airport: "✈️ <strong>Aeroporto Marconi</strong> - 7km",
		location_restaurant_valerio: "🍝 <strong>Trattoria Valerio</strong> - 10m",
		location_restaurant_altrogusto: "🍽️ <strong>L'Altro Gusto</strong> - 200m",
		location_restaurant_pistamentuccia: "🍕 <strong>Pistamentuccia</strong> - 200m",
		location_building_bonasoni: "🏛️ <strong>Palazzo Bonasoni</strong> - 150m",
		location_building_felicini: "🏛️ <strong>Palazzo Felicini</strong> - 150m",
		location_building_merendoni: "🏛️ <strong>Palazzo Merendoni</strong> - 200m",
		location_building_garibaldi: "🗿 <strong>Statua di Garibaldi</strong> - 300m",
		location_building_tuate: "🏠 <strong>Casa delle Tuate</strong> - 300m",
		location_building_dalmonte: "🏛️ <strong>Palazzo dal Monte</strong> - 300m",
		location_building_govese: "🚪 <strong>Porta Govese</strong> - 400m",
		location_building_faccetta: "🏛️ <strong>Palazzo Faccetta Nera</strong> - 450m",
		location_building_nettuno: "⛲ <strong>Statua del Nettuno</strong> - 900m",
        location_restaurants: "🍽️ Ristoranti",
        availability_title: "Disponibilità & Prezzi",
        availability_book_btn: "Prenota",
        rules_title: "Regole e Informazioni",
        rules_times: "🕐 Orari e Check-in",
        rules_arrival: "🕐 <strong>Arrivo:</strong> dalle 15:00 alle 18:00",
        rules_notify: "📞 <strong>Comunicare in anticipo l'orario di arrivo</strong>",
        rules_departure: "🕐 <strong>Partenza:</strong> entro le 11:00",
        rules_no_age_limit: "🔞 <strong>Nessuna età minima per il check-in</strong>",
        rules_not_allowed: "🚫 Non Consentito",
        rules_no_smoking: "🚭 <strong>Fumare non è consentito</strong>",
        rules_no_parties: "🎉 <strong>Non è permesso organizzare feste/eventi</strong>",
        rules_no_pets: "🐕 <strong>Animali non ammessi</strong>",
        rules_no_candles: "🕯️ <strong>Candele e incenso non consentiti</strong>",
        rules_no_loud_music: "🔊 <strong>Musica alta e feste vietate</strong>",
        rules_quiet: "🤫 Orari di Quiete",
        rules_quiet_afternoon: "🕐 <strong>Dalle 14:00 alle 16:00</strong> (riposo pomeridiano)",
        rules_quiet_night: "🌙 <strong>Dalle 23:00 alle 08:00</strong> (riposo notturno)",
        rules_guidelines: "⚠️ Linee Guida",
        rules_only_guests: "👥 <strong>Solo ospiti registrati sono ammessi</strong>",
        rules_slippers: "🥿 <strong>Ciabatte monouso fornite per la camera</strong>",
        rules_no_luggage: "🧳 <strong>Attenzione a non trascinare valigie sul parquet</strong>",
        rules_responsible_use: "🌍 <strong>Uso responsabile di acqua ed elettricità</strong>",
        rules_keys: "🔑 <strong>Attenzione alle chiavi - sostituzione serratura a carico dell'ospite</strong>",
        rules_report_damage: "⚠️ <strong>Comunicare immediatamente danni o incidenti</strong>",
        rules_extra_beds: "🛏️ Letti Aggiuntivi",
        rules_no_extra_beds: "❌ <strong>Non disponibili culle o letti supplementari</strong>",
        faq_title: "Domande Frequenti",
        faq_parking_q: "🅿️ Dove posso parcheggiare?",
        faq_parking_a: "Ci sono parcheggi a pagamento pubblici nel centro storico.",
        faq_wifi_q: "📶 Il WiFi è incluso?",
        faq_wifi_a: "Sì, WiFi veloce gratuito da 343 Mbps disponibile in tutto l'appartamento.",
        faq_ac_q: "❄️ C'è l'aria condizionata?",
        faq_ac_a: "Sì, l'appartamento è dotato di aria condizionata e riscaldamento.",
        faq_elevator_q: "🛗 C'è l'ascensore?",
        faq_elevator_a: "Sì, l'edificio storico del 1890 è dotato di ascensore.",
        faq_extra_beds_q: "🛏️ Sono disponibili letti aggiuntivi?",
        faq_extra_beds_a: "Non sono disponibili letti aggiuntivi.",
        faq_pets_q: "🐕 Posso portare animali?",
        faq_pets_a: "No, gli animali non sono ammessi nell'appartamento.",
        contacts_title: "Contatti",
        contacts_email_label: "Email:",
        contacts_phone_label: "Telefono:",
        contacts_languages_label: "Lingue parlate:",
        contacts_whatsapp_btn: "💬 Scrivici su WhatsApp",
        footer_copyright: "© 2025 B&B Avesella House"
    }
};

function setLanguage(lang) {
    const dict = translations[lang] || translations.en;
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) el.innerHTML = dict[key];
    });
    // Evidenzia la bandiera attiva
    document.getElementById('lang-en').classList.toggle('opacity-50', lang !== 'en');
    document.getElementById('lang-it').classList.toggle('opacity-50', lang !== 'it');
    // Salva preferenza
    localStorage.setItem('lang', lang);
}

document.addEventListener('DOMContentLoaded', function () {
    // Gestione cambio lingua
    const userLang = localStorage.getItem('lang') || 'en';
    setLanguage(userLang);
    document.getElementById('lang-en').onclick = () => setLanguage('en');
    document.getElementById('lang-it').onclick = () => setLanguage('it');
});
